name: Berita

on:
  workflow_dispatch:
  schedule:
    - cron : "0 * * * *"

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
          
      - name: install python packages
        run: |
          cd etl
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute etl py script 
        env:
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
            GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          cd etl
          python etl.py
          
